version: '2'
volumes:
  resin-data:
services:
  web:
    build: ./src/web
    depends_on:
      - iot
    ports:
      - "80:80"
    volumes:
      - "resin-data:/data"
  iot:
    build: ./src/iot
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - "resin-data:/data"
